
version: 2

models:
    - name: bonds_country
      description: no. of bonds by country 
      columns:
          - name: country_iso_alpha2
            description: ISO alpha-2 country code
            tests:
                - unique
                - not_null
