models:
    - name: stg_locations
      description: all shop locations 
      columns:
          - name: id
            description: unique location id
            tests:
                - unique
                - not_null
